sudo: required
services:
  - docker

before_install:
  - docker build -t akshay1818/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true akshay1818/react-test npm run test  -- --coverage

after_success:
  - docker build -t akshay1818/multi-client ./client
  - docker build -t akshay1818/multi-nginx ./nginx
  - docker build -t akshay1818/multi-server ./server
  - docker build -t akshay1818/multi-worker ./worker
  # Login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

  # Take images and push to docker hub
  - docker push akshay1818/multi-client
  - docker push akshay1818/multi-nginx
  - docker push akshay1818/multi-server
  - docker push akshay1818/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-424278061674
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure:  $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
